### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by andysim**
I rebased this to the private repo's master, and I think I have Travis (partially) working.  I wanted to send a PR, in case there are any things in your version of psi4public that shouldn't be pushed yet.  Great work getting Travis started up; I got it working with the following things to be addressed

- [ ] CHEMPS2 has to be disabled for setup to work properly (maybe we need HDF5 or something as a dependency?).
- [x] I disabled concurrent builds, as part of my debugging and have yet to reactivate them, so we need to try that.
- [ ] Make -j2 still hits problems occasionally with libmints expecting a libint.h file that hasn't yet been generated, so I only do serial make right now.  The CMake dependencies look OK to me, so I don't know why we're still seeing problems with this.

The builds you set up are still running [here](https://travis-ci.org/andysim/psi4public/builds), but so far so good.

### CODE REVIEW

**Comment by andysim** [comment]
I'm working on some of Lori's suggestions right now, and will send an updated PR.  Parallel builds seem to be OK, and I reduced the AM.  I'm also trying a couple of things to get the GCC build working.

**Comment by andysim** [comment]
I have a very hacky solution for the Boost linkage error, after many failed attempts.  I added a script that will check out the bundled version, and builds it using -j2.  By adding a user-config.jam in the home area, I can override the compiler settings for the Boost GCC toolset.  We could simply write a user-config.jam file and tell the setup script to build the provided Boost, but that doesn't build Boost in parallel, and introduces the possibility of race conditions.

I reduced the AM requirements in some of the quicktests - if everything passes, could you pull again and get it into the main repo whenever is convenient?

**Comment by jturney** [comment]
Sure thing.

Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA

**Comment by andysim** [comment]
I think I have to make a separate PR, because this one was closed when you did the merge.  I'll make sure everything is working and will create one as soon as it all passes.  Thanks!

**Comment by jturney** [comment]
Sounds good. Once I get it I'll pass it along to the main repo.

Justin Turney, Ph.D.
Senior Research Scientist
CCQC/UGA

**Pull request merged**
